import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";
import mdx from "@astrojs/mdx";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
    site: "https://knicknaks.xanthis.xyz",
    output: "static",
    integrations: [
        react(),
        sitemap(),
        mdx(),
    ],
    redirects: {
        "/tools/age-calculator": "/tools/calculators/age-calculator",
        "/tools/aspect-ratio": "/tools/calculators/aspect-ratio",
        "/tools/base-converter": "/tools/encoders/base-converter",
        "/tools/base64": "/tools/encoders/base64",
        "/tools/bmi-calculator": "/tools/health/bmi-calculator",
        "/tools/bmr-calculator": "/tools/health/bmr-calculator",
        "/tools/body-fat-calculator": "/tools/health/body-fat-calculator",
        "/tools/box-shadow": "/tools/dev/box-shadow",
        "/tools/calorie-calculator": "/tools/health/calorie-calculator",
        "/tools/case-converter": "/tools/text/case-converter",
        "/tools/chmod-calculator": "/tools/dev/chmod-calculator",
        "/tools/color-blindness-simulator": "/tools/color/color-blindness-simulator",
        "/tools/color-converter": "/tools/color/color-converter",
        "/tools/color-harmony": "/tools/color/color-harmony",
        "/tools/compress-pdf": "/tools/pdf/compress-pdf",
        "/tools/contrast-checker": "/tools/color/contrast-checker",
        "/tools/cron-parser": "/tools/dev/cron-parser",
        "/tools/css-filter": "/tools/dev/css-filter",
        "/tools/date-difference-calculator": "/tools/calculators/date-difference-calculator",
        "/tools/deduplicate-lines": "/tools/text/deduplicate-lines",
        "/tools/delete-pdf-pages": "/tools/pdf/delete-pdf-pages",
        "/tools/exif-metadata-viewer": "/tools/media/exif-metadata-viewer",
        "/tools/fancy-text-generator": "/tools/text/fancy-text-generator",
        "/tools/find-replace": "/tools/text/find-replace",
        "/tools/gradient-maker": "/tools/color/gradient-maker",
        "/tools/hash-generator": "/tools/crypto/hash-generator",
        "/tools/html-entities": "/tools/encoders/html-entities",
        "/tools/http-status-codes": "/tools/dev/http-status-codes",
        "/tools/ideal-weight-calculator": "/tools/health/ideal-weight-calculator",
        "/tools/image-color-picker": "/tools/color/image-color-picker",
        "/tools/image-to-pdf": "/tools/pdf/image-to-pdf",
        "/tools/iptv-player": "/tools/media/iptv-player",
        "/tools/json-formatter": "/tools/formatters/json-formatter",
        "/tools/jwt-decoder": "/tools/dev/jwt-decoder",
        "/tools/loan-mortgage-calculator": "/tools/calculators/loan-mortgage-calculator",
        "/tools/lorem-ipsum": "/tools/generators/lorem-ipsum",
        "/tools/markdown-preview": "/tools/text/markdown-preview",
        "/tools/markdown-to-pdf": "/tools/pdf/markdown-to-pdf",
        "/tools/merge-pdf": "/tools/pdf/merge-pdf",
        "/tools/morse-code": "/tools/encoders/morse-code",
        "/tools/number-to-words": "/tools/converters/number-to-words",
        "/tools/pace-calculator": "/tools/health/pace-calculator",
        "/tools/palindrome-anagram": "/tools/text/palindrome-anagram",
        "/tools/password-generator": "/tools/generators/password-generator",
        "/tools/pdf-metadata": "/tools/pdf/pdf-metadata",
        "/tools/pdf-page-numbers": "/tools/pdf/pdf-page-numbers",
        "/tools/pdf-to-images": "/tools/pdf/pdf-to-images",
        "/tools/percentage-calc": "/tools/calculators/percentage-calc",
        "/tools/placeholder-image": "/tools/generators/placeholder-image",
        "/tools/protect-pdf": "/tools/pdf/protect-pdf",
        "/tools/rearrange-pdf": "/tools/pdf/rearrange-pdf",
        "/tools/regex-tester": "/tools/dev/regex-tester",
        "/tools/remove-line-breaks": "/tools/text/remove-line-breaks",
        "/tools/reverse-text": "/tools/text/reverse-text",
        "/tools/roman-numeral": "/tools/converters/roman-numeral",
        "/tools/rot-cipher": "/tools/encoders/rot-cipher",
        "/tools/rotate-pdf": "/tools/pdf/rotate-pdf",
        "/tools/screen-info": "/tools/dev/screen-info",
        "/tools/split-pdf": "/tools/pdf/split-pdf",
        "/tools/string-escaper": "/tools/dev/string-escaper",
        "/tools/tailwind-colors": "/tools/color/tailwind-colors",
        "/tools/text-diff": "/tools/text/text-diff",
        "/tools/text-repeater": "/tools/text/text-repeater",
        "/tools/text-sorter": "/tools/text/text-sorter",
        "/tools/text-to-ascii": "/tools/encoders/text-to-ascii",
        "/tools/text-to-binary": "/tools/encoders/text-to-binary",
        "/tools/text-to-hex": "/tools/encoders/text-to-hex",
        "/tools/text-to-slug": "/tools/text/text-to-slug",
        "/tools/kokoro-tts": "/tools/ai/kokoro-tts",
        "/tools/timezone-converter": "/tools/calculators/timezone-converter",
        "/tools/tip-calculator": "/tools/calculators/tip-calculator",
        "/tools/ulid-generator": "/tools/generators/ulid-generator",
        "/tools/unicode-inspector": "/tools/encoders/unicode-inspector",
        "/tools/unix-timestamp": "/tools/calculators/unix-timestamp",
        "/tools/unlock-pdf": "/tools/pdf/unlock-pdf",
        "/tools/upside-down-text": "/tools/text/upside-down-text",
        "/tools/url-builder": "/tools/dev/url-builder",
        "/tools/url-encoder": "/tools/encoders/url-encoder",
        "/tools/url-parser": "/tools/dev/url-parser",
        "/tools/user-agent-parser": "/tools/dev/user-agent-parser",
        "/tools/uuid-generator": "/tools/generators/uuid-generator",
        "/tools/watermark-pdf": "/tools/pdf/watermark-pdf",
        "/tools/word-counter": "/tools/text/word-counter",
        "/tools/word-to-number": "/tools/converters/word-to-number",
        "/tools/zalgo-text": "/tools/text/zalgo-text",
    },
    vite: {
        plugins: [tailwindcss({
            config: {
                safelist: [
                    { pattern: /(grid-cols|gap)-(1|2|3|4|5|6|7|8|9|10|11|12)/ },
                    { pattern: /(col-span|row-span)-(1|2|3|4|5|6|7|8|9|10|11|12)/ },
                    { pattern: /md:grid-cols-(1|2|3|4|5|6|7|8|9|10|11|12)/ },
                    { pattern: /md:col-span-(1|2|3|4|5|6|7|8|9|10|11|12)/ },
                    { pattern: /md:row-span-(1|2|3|4|5|6|7|8|9|10|11|12)/ },
                    { pattern: /space-y-(1|2|3|4|5|6|7|8|9|10|11|12)/ },
                ]
            }
        })],
        build: {
            target: "es2022",
            cssMinify: true,
        },
    },
});
